# Generated by Django 3.0.4 on 2020-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('coaching_name', models.CharField(max_length=1000)),
                ('school_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('referred_by', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=1000)),
                ('mentor_code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MentorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('why_mentor', models.CharField(max_length=10000)),
                ('linkedin_id', models.CharField(max_length=1000)),
                ('how_mentor', models.BooleanField()),
            ],
        ),
    ]
