# Generated by Django 3.1.1 on 2020-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=100)),
                ('students_number', models.CharField(max_length=10)),
                ('parents_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(default='School', max_length=200)),
                ('referred_by', models.CharField(max_length=100)),
                ('promocode', models.CharField(max_length=100)),
                ('mentor_code', models.CharField(max_length=100)),
                ('laptop', models.CharField(default='Yes,I have a laptop/PC for classes', max_length=100)),
            ],
        ),
    ]
