# Generated by Django 3.0.4 on 2020-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('parents_contact_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('referred_by', models.CharField(max_length=100)),
                ('promocode', models.CharField(max_length=1000)),
                ('mentor_code', models.CharField(max_length=1000)),
            ],
        ),
    ]
