# Generated by Django 3.0.4 on 2020-09-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteedata',
            name='created_at',
        ),
    ]
